version: "3.7"

services:

  flask:
    build: ./flask
    container_name: crcmon_flask
    environment:
      - APP_NAME=crcmonApp
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: crcmon_nginx
    ports:
      - "80:80"

